<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="RSLPTP862" name="JavaProgram9.TimeOutInTestNG" tests="3" failures="0" timestamp="11 Mar 2019 12:50:46 GMT" time="5.164" errors="1">
  <testcase name="test2" time="2.016" classname="JavaProgram9.TimeOutInTestNG"/>
  <testcase name="test3" time="3.016" classname="JavaProgram9.TimeOutInTestNG">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method JavaProgram9.TimeOutInTestNG.test3() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method JavaProgram9.TimeOutInTestNG.test3() didn't finish within the time-out 3000
at java.lang.Thread.interrupt(Thread.java:919)
at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:64)
at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- test3 -->
  <testcase name="test1" time="0.132" classname="JavaProgram9.TimeOutInTestNG"/>
</testsuite> <!-- JavaProgram9.TimeOutInTestNG -->
